### ISSUE TITLE
Provide functions for creating KafkaConsumer test instances

### ISSUE THREAD

**Issue by vlovgr** [fd4s/fs2-kafka#234] opened 2019-10-11 08:02 UTC
It would be useful to provide functions for creating test versions of `KafkaConsumer`.

As a first step, the following function would be a useful addition.

```scala
object KafkaConsumer {
  def fromRecords[F[_], K, V](records: F[ConsumerRecord[K, V]])(
    implicit F: Foldable[F]
  ): KafkaConsumer[F, K, V] =
    ???
}
```

Following, it would be useful to be able to track what offsets have been committed.

**Comment by lewisjkl** [comment] 2020-01-24 03:37
I am starting to take a look at this. I have some ideas of how to take `F[ConsumerRecord[K, V]]` and translate them into a `Stream[F, Stream[F, CommittableConsumerRecord[F, K, V]]]` for the `partitionedStream` method. As long as you don't have any strong opinions about how that is done then I will just take a stab at it and see what you think.

**Comment by lewisjkl** [comment] 2020-01-28 05:44
I took a quick, perhaps somewhat naive, approach to creating the `partitionedStream`. Would love your feedback on this initial solution. I have a few specific questions:

1. I am not sure if there is a better way to build the partitions for the streams. My initial approach has been to require the user to provide a desired number of partitions. From there, map over the provided records to transform them into `CommittableConsumerRecord`s with offsets and partition numbers. Does this seem like a reasonable way to do this or do you have something else in mind?

2. The way that I split the input records into multiple substreams is using `Stream#broadcast`. The only downside to this approach is that it requires a `Concurrent[F]` to work. Is there another way to do this that wouldn't require an extra typeclass constraint? It seems a little unfortunate to need `Concurrent[F]` for a test implementation. Obviously I could perform this split using functions like `List#groupBy`, but I thought it would be nice to use the non-strictness of `Stream` here if possible.

3. I am starting to look at functions like `assignmentStream` and wonder what the expected behavior is there. Are we hoping that we will periodically and randomly perform a fake rebalance and emit elements from that stream? I think it would be really cool, but I also don't want to overdo it here.

Keep in mind that this is mainly just a quick pass at an implementation to start a discussion about possible solutions. And also there could be errors here because I still need to write tests 🙂

**Comment by mwz** [comment] 2020-02-07 17:07
> 1\. I am not sure if there is a better way to build the partitions for the streams. My initial approach has been to require the user to provide a desired number of partitions.

I guess you can infer the number of partitions from the supplied records, so there's probably no need to ask for it explicitly.

> 2\. The way that I split the input records into multiple substreams is using `Stream#broadcast`. The only downside to this approach is that it requires a `Concurrent[F]` to work. Is there another way to do this that wouldn't require an extra typeclass constraint?

Personally, I'd probably go for a simple implementation here and avoid introducing `Concurrent`. I'm not sure if you can benefit much from the non-strictness of Streams in tests where the records will most likely consist of a small number of elements. Even if you use generators, there's probably still not much to be gained there. Also, instead of flattening the partitioned stream (as in your PR), you can probably interleave the substreams to introduce some sort of (fake) notion of concurrency in the consumer (instead of concatenating them with each other).

> 3\. I am starting to look at functions like `assignmentStream` and wonder what the expected behavior is there. Are we hoping that we will periodically and randomly perform a fake rebalance and emit elements from that stream?

I wouldn't expect this kind of behaviour from this test consumer. Rebalancing behaviour might be probably something you could test using an actual consumer (obtained from the `ConsumerStream`) with embedded kafka; I'd keep this consumer fairly simple. From my point of view, the bare minimum I'd want from this test instance to do is to essentially implement the `subscribe` and `stream/partitionedStream` functions to give me a stream of committable records. The ability to track committed offsets and emulate a commit failure would be also useful, but not essential initially. Obviously, others might have more sophisticated use cases, so it would be useful to hear some feedback from other users.

**Comment by lewisjkl** [comment] 2020-02-07 19:45
Thanks @mwz for your feedback! I’ll take that into account. Should be much easier to get this PR done now that I’m not worried about mimicking rebalance behavior and such.

**Comment by aartigao** [comment] 2023-09-29 18:40
I'm closing this issue because the preferred way is by using [fs2-kafka-mock](https://index.scala-lang.org/jchapuis/fs2-kafka-mock).

We can always reopen it to discuss, but given it hasn't received love for +3 years, I think it's best to close it and open the discussions in fs2-kafka-mock if something is missing to avoid multiple solutions for the same problem 🙏🏽

**Closed by aartigao** 2023-09-29 18:40 UTC
Labels: good first issue
